export const ADD_STICKY = 'ADD_STICKY';
export const GET_STICKY = 'GET_STICKY';
export const MODIFY_STICKY_TITLE = 'MODIFY_STICKY_TITLE';
export const MODIFY_STICKY_CONTENTS = 'MODIFY_STICKY_CONTENTS';
export const HIDE_STICKY_CONTENTS = 'HIDE_STICKY_CONTENTS';
export const MOVE_STICKY = 'MOVE_STICKY';
export const RESIZE_STICKY = 'RESIZE_STICKY';
export const REMOVE_STICKY = 'REMOVE_STICKY';
